version: '3'
services:
  web:
    container_name: app
    build: 
      context: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
      