version: '3'
services:
  web:
    container_name: app
    image: app:v1
    build: 
      context: app
    restart: always
    ports:
      - "8080:8080"
    # build fails but implementation works somehow
    # env_file:
    #   - ~/.env
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_IP=$MONGO_IP
  # No need since we already installed MongoDB in EC2
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
      